# Generated by Django 3.2.24 on 2024-02-29 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=50)),
                ('tipocliente', models.CharField(choices=[('hogar', 'Hogar'), ('empresa', 'Empresa')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('portatil', 'Portátil'), ('pc_escritorio', 'PC de escritorio'), ('impresora', 'Impresora'), ('componente', 'Componente'), ('otros', 'Otros')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('observacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion_corta', models.CharField(max_length=100)),
                ('estado_fisico', models.CharField(max_length=80)),
                ('componente_adjunto', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('remoto', 'Remoto'), ('taller', 'Taller'), ('insitu', 'In Situ')], max_length=10)),
                ('estado', models.CharField(blank=True, choices=[('no_iniciado', 'No Iniciado'), ('en_proceso', 'En Proceso'), ('confirmacion', 'Esperando Confirmación del Cliente'), ('aprobado_por_cliente', 'Aprobado por el Cliente'), ('finalizado', 'Finalizado'), ('anulado', 'Anulado')], default='no_iniciado', max_length=30, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultado_incidencia', models.TextField(blank=True, null=True)),
                ('sugerencias', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.cliente')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketsoporte.dispositivo')),
            ],
        ),
    ]
